# ArgoCD Application for DEV HPA (Horizontal Pod Autoscaling)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtorque-autoscaling-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/TechTorque-2025/k8s-config.git
    targetRevision: dev
    path: k8s/autoscaling
    directory:
      include: 'hpa-dev.yaml'  # Deploy lightweight HPA for dev environment
      exclude: '{hpa-azure-optimized.yaml,hpa.yaml,*.md,*.sh}'  # Exclude prod HPA and other files
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
