# ArgoCD Application for DEV Database Deployments
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtorque-databases-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/TechTorque-2025/k8s-config.git
    targetRevision: dev
    path: k8s/databases
  destination:
    server: https://kubernetes.default.svc
    namespace: dev  # Separate dev databases
  syncPolicy:
    automated:
      prune: false  # Don't auto-delete databases for safety
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
