# Example GitHub Actions Workflow with ArgoCD Integration
# Place this in: .github/workflows/deploy-service.yaml

name: Build and Deploy Service

on:
  push:
    branches:
      - main
    paths:
      - 'services/auth-service/**'  # Adjust path to your service
      - 'k8s-config/k8s/services/auth-deployment.yaml'

env:
  REGISTRY: ghcr.io
  SERVICE_NAME: auth_service
  IMAGE_NAME: ghcr.io/techtorque-2025/auth_service

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=sha-
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./services/auth-service
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Kubernetes manifest
        run: |
          # Get the Git SHA
          GIT_SHA=$(git rev-parse --short HEAD)

          # Update the image tag in the deployment manifest
          sed -i "s|image: ghcr.io/techtorque-2025/auth_service:.*|image: ghcr.io/techtorque-2025/auth_service:sha-$GIT_SHA|" \
            k8s-config/k8s/services/auth-deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add k8s-config/k8s/services/auth-deployment.yaml
          git commit -m "Update auth-service image to sha-${{ github.sha }}" || exit 0
          git push

  # Optional: Trigger immediate ArgoCD sync (instead of waiting 3 minutes)
  sync-argocd:
    needs: update-manifest
    runs-on: ubuntu-latest
    if: false  # Set to 'true' to enable ArgoCD webhook sync

    steps:
      - name: Trigger ArgoCD Sync
        run: |
          curl -X POST https://your-argocd-domain.com/api/webhook \
            -H "Content-Type: application/json" \
            -d '{
              "application": "techtorque-services",
              "revision": "main"
            }'

---
# Alternative: Using ArgoCD Image Updater
# This approach doesn't require GitHub Actions to update manifests
# ArgoCD Image Updater watches the container registry and updates Git automatically

# Add this annotation to your deployment:
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: auth-deployment
#   annotations:
#     argocd-image-updater.argoproj.io/image-list: auth=ghcr.io/techtorque-2025/auth_service
#     argocd-image-updater.argoproj.io/auth.update-strategy: digest
#     argocd-image-updater.argoproj.io/auth.allow-tags: regexp:^sha-[a-f0-9]{7}$

# Then install ArgoCD Image Updater:
# kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/stable/manifests/install.yaml
